// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cawsioxnlhipteudlzce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhd3Npb3hubGhpcHRldWRsemNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzE2MDgsImV4cCI6MjA1NDk0NzYwOH0.TV7isoQr_nYLaOVfOJNOyOGjpvmVuI7kb-2v5IDQtAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);